#!/bin/sh

# Wrapper to use curl with the Mastodon API. Setup steps:
#
# 1. Create an app:
#
#     tusk -A myapp.json -n 'My App'
#
# Specifying the app name with -n is required; specifying a website with
# -w or changing the scope from the default of 'read write' with -s are
# optional.
#
# 2. Create an access token as your user to post as the app: (for this
# step, be logged in to a browser as the bot or other user you want the
# token to apply to)
#
#     tusk -a myapp.json -T token.json
#
# 3. Use the token as your bot:
#
#     tusk -t token.json /accounts/verify_credentials
#
# Or, more generally,
#
#     tusk -t TOKEN_FILE API_RESOURCE [CURL_OPTIONS...]
#
# That's it! To help you remember the setup options: capital letters
# will write files (without asking to overwrite, so be careful!), and
# lowercase letters will read those files. You need one app JSON file
# for each piece of code (bot/script/whatever) and then, for each app,
# one token for each user account that wants that code to do something
# on its behalf. It's up to you where to store them.

case $* in --help) exec sed '1,2d;/^$/,$d;s/^#/ /' "$0"; esac

instance=https://mastodon.social
app_scopes='read write'
while getopts i:A:a:n:w:s:T:t:r: opt; do
    case $opt in
        i) instance=$OPTARG;;
        A) app_file=$OPTARG; create_app=yes;;
        a) app_file=$OPTARG;;
        n) app_name=$OPTARG;;
        w) app_website=$OPTARG;;
        s) app_scopes=$OPTARG;;
        T) token_file=$OPTARG; create_token=yes;;
        t) token_file=$OPTARG;;
        ?) echo "Unknown option: $opt" 1>&2; exit 2;;
    esac
done; shift $(($OPTIND - 1))

oob=urn:ietf:wg:oauth:2.0:oob
auth_base_uri=$instance/oauth
api_base_uri=$instance/api/v1

umask 077

create_app() {
    curl --data-urlencode client_name="$app_name" \
         --data-urlencode redirect_uris="$oob" \
         --data-urlencode scopes="$app_scopes" \
         ${app_website:+--data-urlencode client_website="$app_website"} \
         -s "$api_base_uri"/apps > "$app_file" || exit 3
    echo "OK! Created app #$(jq -r .id "$app_file") with client ID $(jq .client_id "$app_file")"
}

create_token() {
    client_id=$(jq -r .client_id "$app_file")
    query=$(curl -w '%{url_effective}' --data-urlencode client_id="$client_id" \
                 --data-urlencode response_type=code \
                 --data-urlencode redirect_uri="$oob" \
                 --data-urlencode scope="$app_scopes" -G / | cut -c 3-)
    echo "Open this URL in the browser where you are logged in..."
    echo "    $auth_base_uri/authorize?$query"
    printf '%s: ' 'Please enter the code you got'; read code
    client_secret=$(jq -r .client_secret "$app_file")
    curl --data-urlencode grant_type="authorization_code" \
         --data-urlencode client_id="$client_id" \
         --data-urlencode client_secret="$client_secret" \
         --data-urlencode code="$code" \
         --data-urlencode redirect_uri="$oob" \
         -s "$auth_base_uri/token" > "$token_file" || exit 3
    access_token=$(jq -r .access_token "$token_file")
    echo "OK! Created $(jq .token_type "$token_file") token with scope $(jq .scope "$token_file")"
}

if test -n "$app_file" -a -n "$create_app"; then
    create_app
elif test -n "$token_file" -a -n "$create_token"; then
    create_token
elif test -e "$token_file"; then
    access_token=$(jq -r .access_token "$token_file")
    resource=${1#/}; shift
    curl -H "Authorization: Bearer $access_token" "$api_base_uri/$resource" "$@"
else
    echo "Please create an app and/or token (see --help for instructions)" 2>&1
    exit 2
fi
